version: 2.1.0-{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_branch_with_pr: true
image: Visual Studio 2019
configuration: Release
environment:
  nodejs_version: "10"
install:
- ps: Install-Product node $env:nodejs_version
- ps: '"//registry.npmjs.org/:_authToken=$env:npm_auth_token`n" | out-file "$env:userprofile\.npmrc" -Encoding ASCII'
- npm whoami
nuget:
  disable_publish_on_pr: true
before_build:
- ps: nuget restore Machine.sln
- ps: |
    cd src\SIL.Machine.TS
    npm --loglevel=error install
    cd ..\..
build:
  project: Machine.sln
  verbosity: minimal
test_script:
- ps: |
    $failed = $FALSE
    dotnet test --no-build -c Release --test-adapter-path:. --logger:Appveyor tests\SIL.Machine.Tests\SIL.Machine.Tests.csproj
    if (-not $?) { $failed = $TRUE }
    dotnet test --no-build -c Release --test-adapter-path:. --logger:Appveyor tests\SIL.Machine.Morphology.HermitCrab.Tests\SIL.Machine.Morphology.HermitCrab.Tests.csproj
    if (-not $?) { $failed = $TRUE }
    dotnet test --no-build -c Release --test-adapter-path:. --logger:Appveyor tests\SIL.Machine.Translation.Thot.Tests\SIL.Machine.Translation.Thot.Tests.csproj
    if (-not $?) { $failed = $TRUE }
    dotnet test --no-build -c Release --test-adapter-path:. --logger:Appveyor tests\SIL.Machine.WebApi.Tests\SIL.Machine.WebApi.Tests.csproj
    if (-not $?) { $failed = $TRUE }

    cd src\SIL.Machine.TS
    npm run test:ci
    if (-not $?) { $failed = $TRUE }
    cd ..\..
    $wc = New-Object 'System.Net.WebClient'
    $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\src\SIL.Machine.TS\junit.xml))
    if ($failed) { throw "The unit tests failed." }

deploy_script:
- ps: |
    if ($env:publish_packages -eq "true")
    {
        dotnet pack src\SIL.Machine\SIL.Machine.csproj -c Release -o artifacts --version-suffix $env:APPVEYOR_BUILD_NUMBER
        dotnet pack src\SIL.Machine.Translation.Thot\SIL.Machine.Translation.Thot.csproj -c Release -o artifacts --version-suffix $env:APPVEYOR_BUILD_NUMBER
        dotnet pack src\SIL.Machine.WebApi\SIL.Machine.WebApi.csproj -c Release -o artifacts --version-suffix $env:APPVEYOR_BUILD_NUMBER
        dotnet pack src\SIL.Machine.Morphology.HermitCrab\SIL.Machine.Morphology.HermitCrab.csproj -c Release -o artifacts --version-suffix $env:APPVEYOR_BUILD_NUMBER

        Get-ChildItem artifacts\*.* | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

        cd src\SIL.Machine.TS
        npm version $env:APPVEYOR_BUILD_VERSION
        npm publish --access public
        cd ..\..
    }
